### ISSUE TITLE
Write code to actually login

### ISSUE THREAD

**Issue by steevejoseph** [steevejoseph/contact-manager#28]
This issue captures the full login process.
1. User shown form.
2. User submits form.
3. Password hashed (user auth)
4. DB is queried for user+combo
5. Session is established.
6. User redirected to homepage, with their personalized info displayed.

**Comment by alittlebirdie00** [comment]
@steevejoseph Is this done?

**Comment by nyashafrank** [comment]
Can we close this since the functionality works?

**Comment by steevejoseph** [comment]
Yerrrrrr, closing rn.
